using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System;

#nullable disable

namespace QuizWiz_Backend.Migrations
{
    public partial class ChangeQuestionIdToGuid : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Usuwamy powiązanie IDENTITY z kolumny id (PostgreSQL wymaga tego przed zmianą typu)
            migrationBuilder.Sql("ALTER TABLE questions ALTER COLUMN id DROP IDENTITY IF EXISTS;");

            // 2. Zmieniamy typ kolumny id z integer na uuid, generując losowe UUID za pomocą wbudowanej funkcji gen_random_uuid() 
            // (Dzięki temu jeśli w bazie były jakieś rekordy, otrzymają one poprawne, unikalne wartości Guid zamiast błędów konwersji)
            migrationBuilder.Sql("ALTER TABLE questions ALTER COLUMN id TYPE uuid USING gen_random_uuid();");

            // 3. Upewniamy się, że kolumna nie zezwala na wartości NULL
            migrationBuilder.AlterColumn<Guid>(
                name: "id",
                table: "questions",
                type: "uuid",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Powrót do typu int (w razie rollbacku)
            migrationBuilder.Sql("ALTER TABLE questions ALTER COLUMN id TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AlterColumn<int>(
                name: "id",
                table: "questions",
                type: "integer",
                nullable: false)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}